POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer

{
  "title": "blogin lisääminen 3",
  "author": "mluukkai",
  "url": "https://fullstackopen.com/osa4/token_perustainen_kirjautuminen#tehtavat-4-15-4-23"
}